nname: Clone Repository and Markdown
on:
  push:
    branches:
      - Testapplications_for_Uni
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Clone repository
        run: git clone https://github.com/Sciebo-RDS/rds-ng.git
      
      - name: Install docstring-markdown
        run: pip install pydoc-markdown
      - name: Go to directory
        run: cd rds-ng/docs
      - name: Generate markdown 
        run: pydoc-markdown  
      - name: Build Docusaurus # create weg, stattdessen build docusaurus
        run: npm run build      
      # brauchen wir das hier wirklich?
      #- name: Setup Node.js
      #  uses: actions/setup-node@v3
      #  with:
      #    node-version: 18 

      # brauchen wir das hier wirklich?
      #- name: Install Dependencies
      #  run: npm install


        
    

## als nächstes:
## clonen des GH Pages repository
## kopieren der markdown files in das GH Pages repository
## Pushen nach GH pages 
## https://github.com/marketplace/actions/github-pages-action
## https://docs.github.com/en/actions/security-guides/automatic-token-authentication
