name: Clone Repository and Markdown
on:
  push:
    branches:
      - Testapplications_for_Uni
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Clone repository
        run: git clone https://github.com/Sciebo-RDS/rds-ng.git ./reposit01
      
      - name: Install docstring-markdown
        run: pip install pydoc-markdown
      - name: Generate Markdown from docstrings
        run: pydoc-markdown ./reposit01 --output ./docs  
