name: Clone Repository and Markdown
on:
  push:
    branches:
      - Testapplications_for_Uni
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Clone repository
        run: git clone https://github.com/Soroush9978/rds-ng
      
      - name: Install docstring-markdown
        run: pip install pydoc-markdown
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 
      - name: Generate markdown 
        run: pydoc-markdown -I rds-ng/docs

     

      - name: Install Dependencies
        run: |
         cd rds-ng/docs
         npm install
         npm run build    
      
      #- name: Build Docusaurus # create weg, stattdessen build docusaurus
       # run: npm run build      
## als nächstes:
## clonen des GH Pages repository
## kopieren der markdown files in das GH Pages repository
## Pushen nach GH pages 
## https://github.com/marketplace/actions/github-pages-action
## https://docs.github.com/en/actions/security-guides/automatic-token-authentication
